FROM alpine:3.5

WORKDIR /app

COPY app/ /app/
COPY data/ /data/

ENV DNSMASQ_RCACHE 1000
ENV DNSMASQ_VERBOSE true
ENV DNSMASQ_RCACHE_TTL 30
ENV DNSMASQ_ENABLE_SEARCH true
ENV DNSMASQ_SERVERS 8.8.8.8,8.8.4.4
ENV DNSMASQ_LISTEN 0.0.0.0
ENV DNSMASQ_HOSTSFILE /data/dnsmasq.conf
ENV DNSMASQ_POLL 300

EXPOSE 53 53/udp

ENV PATH /app:$PATH

ENTRYPOINT ["webproc"]

CMD ["webproc","/data/program.toml"]
